apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.9.0
    helm:
      parameters:
      - name: identityTrustAnchorsPEM 
        value: | # Replace value below with generated sample-trust.crt value 
          -----BEGIN CERTIFICATE-----
          MIIBjjCCATSgAwIBAgIRAMfoOE2pn+cu13r8rhOQQYcwCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjQwMTI2MTkz
          MjU0WhcNMjkwMTI0MTkzMjU0WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPtDbRLNK1Xkl5Qx
          4VI17TmMokWaYZ88cbFf/FysgJbEFlwVRSkC2NxkNpTiyGoOc5/TA0SixukobQcf
          3CdeGlSjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBTsgmCpd4VSDcnjSJEWunn05DFDkTAKBggqhkjOPQQDAgNIADBFAiEA
          pHzcx2oTNvcbYuRODRvWn/zFQvQkRHKql1aF9CsX5tQCIH14DAhTHREo0fhhXvBF
          +3HZPw1FyFF5SKNts3zuXVX8
          -----END CERTIFICATE-----
      - name: identity.issuer.scheme
        value: kubernetes.io/tls
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: ""
    kind: Secret
    name:  linkerd-proxy-injector-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-sp-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-policy-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name:  linkerd-proxy-injector-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-sp-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-policy-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true