apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.4.0
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: ""
    kind: CustomResourceDefinition
    name:  authorizationpolicies.policy.linkerd.io
    jsonPointers:
    - /spec/names/shortNames
  - group: ""
    kind: CustomResourceDefinition
    name:  meshtlsauthentications.policy.linkerd.io
    jsonPointers:
    - /spec/names/shortNames
  - group: ""
    kind: CustomResourceDefinition
    name:  networkauthentications.policy.linkerd.io
    jsonPointers:
    - /spec/names/shortNames
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true