apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 56.2.1
    helm:
      valueFiles:
      - $values/resources/prometheus/values.yaml
  - repoURL: 'https://github.com/angelopaolosantos/argocd-app-config.git'
    targetRevision: main
    path: resources/prometheus/
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true