apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
  - chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.3.1
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: HEAD
    path: apps/cert-manager/
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
  syncOptions:
  - CreateNamespace=true
  - ApplyOutOfSyncOnly=true