apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
  - chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.8.0
  - chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.16.10
    helm:
      valueFiles:
      - $values/apps/linkerd/values.yaml
  - repoURL: 'https://github.com/angelopaolosantos/argocd-app-config.git'
    targetRevision: main
    path: apps/linkerd/
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
  syncOptions:
  - CreateNamespace=true
  - ApplyOutOfSyncOnly=true